export default [
  {
    id: 0,
    name: "",
    description: "3D Model",
    image: "images/projects/img_1.jpg",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 1,
    name: "",
    description: "3D Model",
    image: "images/projects/img_2.jpg",
    tags: [],
    liveview: "https://cryptomines.app/",
    alt: "Mint NFTs, Explore Planets portfolio project",
  },
  {
    id: 2,
    name: "",
    description: "3D Model",
    image: "images/projects/img_3.jpg",
    tags: [],
    liveview: "https://glovoapp.com/",
    alt: "Food Delivery portfolio project",
  },
  {
    id: 4,
    name: "",
    description:
      "3D Model",
    liveview: "https://www.drumelia.com/",
    image: "images/projects/img_4.jpg",
    tags: [],
    alt: "This is the Luxury Real Estate website",
  },
  {
    id: 5,
    name: "",
    description:
      "3D Model",
    liveview: "https://www.dexify.finance/",
    image: "images/projects/img_5.jpg",
    tags: [],
    alt: "Dexify Finance",
  },
  {
    id: 6,
    name: "",
    description:
      "3D Model",
    image: "images/projects/img_6.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Furry 3D Model",
    image: "images/projects/img_7.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Furry 3D Model",
    image: "images/projects/img_8.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Furry 3D Model",
    image: "images/projects/img_9.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Furry 3D Model",
    image: "images/projects/img_10.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_11.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_12.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_13.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Vtuber Model",
    image: "images/projects/img_14.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_15.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
      "Vtuber Model",
    image: "images/projects/img_16.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_17.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Vtuber Model",
    image: "images/projects/img_18.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },

  {
    id: 6,
    name: "",
    description:
    "Cover Design",
    image: "images/projects/img_19.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Banner Design",
    image: "images/projects/img_20.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Banner Design",
    image: "images/projects/img_21.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Logo Design",
    image: "images/projects/img_22.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Logo Design",
    image: "images/projects/img_23.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Logo Design",
    image: "images/projects/img_24.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_25.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_26.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_27.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_28.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_29.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_30.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_31.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_32.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_33.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_34.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_35.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Mascot Logo Design",
    image: "images/projects/img_36.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_37.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_38.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_39.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_40.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_41.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Illustration",
    image: "images/projects/img_42.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_43.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_44.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_45.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_46.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_47.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_48.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Overaly Design",
    image: "images/projects/img_49.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Emotes Design",
    image: "images/projects/img_50.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Emotes Design",
    image: "images/projects/img_51.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Emotes Design",
    image: "images/projects/img_52.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Emotes Design",
    image: "images/projects/img_53.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Emotes Design",
    image: "images/projects/img_54.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Gore Art Design",
    image: "images/projects/img_55.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Anime Kinda Art Design",
    image: "images/projects/img_56.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 6,
    name: "",
    description:
    "Anime Kinda Art Design",
    image: "images/projects/img_57.jpg",
    liveview: "https://nftshowroom.com/",
    tags: [],
    alt: "",
  },
  {
    id: 60,
    name: "",
    description: "Montage Video",
    video: "images/projects/video_2.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Montage Video",
    video: "images/projects/video_1.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Montage Video",
    video: "images/projects/video_3.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Animated Emotes",
    video: "images/projects/video_4.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Animated Emotes",
    video: "images/projects/video_5.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Animated Emotes",
    video: "images/projects/video_6.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "Animated Emotes",
    video: "images/projects/video_7.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },
  {
    id: 60,
    name: "",
    description: "3D Rigging Video",
    video: "images/projects/video_8.mp4",
    tags: [],
    liveview: "https://osso-heco.webflow.io/",
    alt: "Hospital website portfolio project",
  },

  
  
  
  
];
