export default {
  html: `<div class="work-item-tag" style="background: #80bf99; border: 1px solid #7C8594; color: #7C8594">HTML</div>`,
  css: `<div class="work-item-tag" style="background: #4785b8; border: 1px solid #7C8594; color: #7C8594">CSS</div>`,
  webgl: `<div class="work-item-tag" style="background: #5A69EC;">WebGL</div>`,
  Next: `<div class="work-item-tag" style="background: #f2f29e;">Next</div>`,
  Solidity: `<div class="work-item-tag" style="background: #8cffbf;">Solidity</div>`,
  Wordpress: `<div class="work-item-tag" style="background: #1a8ce6;">Wordpress</div>`,
  Jquery: `<div class="work-item-tag" style="background: #7a33f0;">Jquery</div>`,
  Laravel: `<div class="work-item-tag" style="background: #6beb75;">Laravel</div>`,
  Django: `<div class="work-item-tag" style="background: #7da3ab;">Django</div>`,
  Vue: `<div class="work-item-tag" style="background: #eb2999;">Vue</div>`,
  AutoCad: `<div class="work-item-tag" style="background: #85d147;">AutoCad</div>`,
  ThreeDSMax: `<div class="work-item-tag" style="background: #1affa3;">3DS Max</div>`,
  SketchUp: `<div class="work-item-tag" style="background: #ff9933;">Sketch Up</div>`,
  AutodeskRevit: `<div class="work-item-tag" style="background: #21BAEB;">Revit</div>`,
  Photoshop: `<div class="work-item-tag" style="background: #CA49F8;">Photoshop</div>`,
  Blender: `<div class="work-item-tag" style="background: #FFB800;">Blender</div>`,
  Maya: `<div class="work-item-tag" style="background: #8433CC;">Maya</div>`,
  Vray: `<div class="work-item-tag" style="background: #ff33ff;">Vray</div>`,
  DialUx: `<div class="work-item-tag" style="background: #f2076e;">Dial Ux</div>`,
  GemEditor: `<div class="work-item-tag" style="background: #7accd6;">Gem Editor</div>`,
};
